# Row reduction and LU Decomposition

```{julia}
#| label: setup
# Load packages.
using LinearAlgebra
```
## Key points

- When working with a system of matrices, we need to apply manipulations to both sides and in the same order -- they are noncommunicative.
- Row reduction allows us to take the rows of matrix $A$ and scalar multiply then add them until we have an upper-triangular matrix, $U$. The linear transformations can be recorded in our transformation matrix,, $L$, which left multiplies $A$. That is $L^{-1}A = U$
- We use row reduction in LU decomposition. The result is unique so long as there is a square and full rank matrix.

## Systems of equations

- LU decomposition is essentially solving a series of systems of equations. Here's some examples of how to algebraically solve them.

$$
\begin{aligned}
    x = 4-y\\
    y = \frac{x}{2} + 2\\
    \\
    x = 4 - (\frac{1}{2}x + 2) \\
    \frac{3}{2}x = 4 - 2\\
    x = \frac{4}{3}\\
    y = \frac{4}{3}^{-2} + 2 \\
    y = \frac{2}{3} + \frac{6}{3} = \frac{8}{3}
\end{aligned}
$$

## Matrices as systems
- Take the following system:
$$
\begin{aligned}
    x + y = 4 \\
    -\frac{x}{2} + y = 4\\
\end{aligned}
$$
    - In matrix form, it would be re-expressed as:
$$
\begin{bmatrix}
    1&1\\
    -\frac{1}{2}&1
\end{bmatrix}\begin{bmatrix}
    x\\
    y
\end{bmatrix} = \begin{bmatrix}
    4\\
    2
\end{bmatrix}
$$
- You essentially create a matrix of scalars, then a column vector of variables which is equivalent to the vector of scalars.
- This is what is represented when we have $Ax = b$.
    - $A$ is our matrix of scalars called our coefficients.
    - $x$ is our vector of variables.
    - $b$ is our vector of constants.

### Working with/solving matrices as systems
- What you do to one-side, you must do to the other.
- The order matters. If you pre-multiply a matrix/vector on one-side you have to do it on the other.
    - E.g.
        - The following is valid.
    $$
    \begin{aligned}
        AX = B\\
        CAX = CB\\
    \end{aligned}
    $$
        - The following is invalid.
    $$
    \begin{aligned}
        AX = B\\
        AXC = CB\\
    \end{aligned}
    $$

### Row reduction

::: {.callout-note title="Definitions"}
Echelon form matrix
    - The resulting upper triangular matrix from row reduction
    - The leftmost nonzero number in a row (called the pivote) is to the right of the pivote of the rows above.
    - Any rows of all zerios are below rows containing nonzeros.
:::

- The building block for LU decomposition.
- It is the way to solve systems of equations by hand and is very well-known in linear algebra. However, you often do not actually do it by hand. It is useful to know about as it leads to LU decomposition.
- Row reduction
    - You iteratively apply two operations to rows of a matrix:
        1. scalar multiplication
        2. scalar addition
    - It is the matrix system way of adding equations to other equations within a system (solving a system with substitution).
    - The goal of row reduction: transform a dense matrix into a upper-triangular matrix via row manipulations that we implement by premultiplying a transformation matrix.
- Example:
    $$
    \begin{bmatrix}
        2&3\\
        -2&2\\
    \end{bmatrix} \xrightarrow{R_1 + R2} \begin{bmatrix}
        2&3\\
        0&5\\
    \end{bmatrix}
    $$
    - We get this upper triangular matrix by adding the first row to the second row.
    - This upper triangular matrix is called the **echelon form** of the matrix
- Though the echelon form is different than the original matrix, it is connected to the original matrix through a linear combination. We can represent this as:
$$
\begin{bmatrix}
    1&0\\
    1&1\\
\end{bmatrix}\begin{bmatrix}
    2&3\\
    -2&2\\
\end{bmatrix} = \begin{bmatrix}
    2&3\\
    0&5\\
\end{bmatrix}
$$
    - This is often represented as $L^{-1}A = U$ where $L^{-1}$ represents the linear transformations that we have implemented as a way to keep track of what manipulations we have done with row reduction.
- The problem with row reduction is that it is tedius and that the echelon form of a matrix is not unique.

## Gaussian Elimination
- You do not have to do matrix inversion to solve a matrix equation.
- We can use Gaussian Elimination.
- How?
    - Augment the matrix of coefficeints by the vector of constants, row reduce to echelon form, then use back substitution to solve for each variable.

- Example:

$$
\begin{aligned}
    x = 4-y\\
    y = \frac{x}{2} + 2\\
    \text{Put in matrix form:}\\
    \begin{bmatrix}
        1&1\\
        -\frac{1}{2}&1\\
    \end{bmatrix}\begin{bmatrix}
        x\\
        y\\
    \end{bmatrix} = \begin{bmatrix}
        4\\
        2\\
    \end{bmatrix}\\
    \begin{bmatrix}
        1&1\\
        -\frac{1}{2}&1\\
    \end{bmatrix} \sqcup \begin{bmatrix}
        4\\
        2\\
    \end{bmatrix} = \begin{bmatrix}
        1&1&4\\
        -\frac{1}{2}&1&2\\
    \end{bmatrix}\\
    \text{Row reduce:}\\
    \begin{bmatrix}
        1&1&4\\
        -\frac{1}{2}&1&2\\
    \end{bmatrix} \xrightarrow{\frac{1}{2}R_1 + R_2} \begin{bmatrix}
        1&1&4\\
        0&\frac{3}{2}&4\\
    \end{bmatrix}\\
    \text{Back substitute:}\\
    x + y = 4\\
    \frac{3}{2}y = 4 \Rightarrow y =  \frac{8}{3} \\
    x + \frac{8}{3} = 4 \Rightarrow x = \frac{4}{3} \\
    \Rightarrow \begin{bmatrix}
        1&1&4\\
        0&1&\frac{8}{3}\\
    \end{bmatrix}
\end{aligned}
$$

## Gauss-Jordan Elimination
- We need to keep reducing so that the left-most nonzero elements in the matrix, our pivots, are 1s.
- After back substitution, to find the constant for X we can use a shortcut by dividing each row by it's pivot. So, for example, we had been here:
$$
\begin{bmatrix}
    1&1&4\\
    0&1&\frac{8}{3}
\end{bmatrix}
$$
- We can use Gauss-Jordan elimination as a trick to continue row reducing upward to get rid of elements abov each pivot.
$$
\begin{bmatrix}
    1&1&4\\
    0&1&\frac{8}{3}
\end{bmatrix} \xrightarrow{-R_2 + R_1} \begin{bmatrix}
    (-0+1)&(-1+1)&(-\frac{8}{3}+\frac{12}{3})\\
    0&1&\frac{8}{3}\\
\end{bmatrix}=\begin{bmatrix}
    1&0&\frac{4}{3}\\
    0&1&\frac{8}{3}\\
\end{bmatrix}
$$
- Like back substitution, this produces a reduced row echelon form, RREF.
- Remember Gauss-Jordan Elimination is just the shortcut that we can use to solve a matrix system rather than having to go back to solving a system of equations.
## Matrix inverse via Gauss-Jordan Eliminations:
- Say that we have this:
$$
\begin{bmatrix}
    a&b\\
    c&d\\
\end{bmatrix}\begin{bmatrix}
    x_1\\
    y_1\\
\end{bmatrix} = \begin{bmatrix}
    1\\
    0
\end{bmatrix}
$$
- The constants vector is the first column vector for a $2\times 2$ $I$.
- What this implies is that applying RREF to a square full-rank matrix augmented by the first column of the identity matrix will show the linear transformation that generates the matrix into the first column of the identity matrix. This then means that the vector $[x_1 y_1]^T$ is the first column of the matrix inverse. We can then repeat this process but for the second column of the inverse.
- Basically, this is a mechanism to find the matrix inverse without computing determinants. The draw back is that row redeuction involves a lot of division which can lead to error from lack of precision. Though it is more numerically stable than the inverse. A matrix that is close to singular or one that has a high condition number will be difficult to inverse no matter what!

## LU Decomposition
- Builds on row reduction by adding constraints. Doing this allows us to identify a unique echelon form, unlike what we get with row reduction alone. This is the RREF and $U$.
- The goal with this procedure is to decompose a given matrix into the product of two triangular matrices.
- It relies upon row reduction.
- The echelon form is not necessarily unique with LU decomposition.
    - However, by requiring that the diagonals of $L$ are 1, this makes sure that the LU decomposition is unique for a full-rank square matrix.
$$
A = LU
$$
- A numerical example:
    - We have the following matrix:
$$
\begin{bmatrix}
    2&2&4\\
    1&0&3\\
    2&1&2\\
\end{bmatrix}
$$
    - We can do $L^{-1}A=U$ with row reduction like before to get the transformation matrix  that transforms $A$ into the echelon form, $U$ (which is an upper-triangle).

$$
\begin{bmatrix}
    2&2&4\\
    1&0&3\\
    2&1&2\\
\end{bmatrix} = \begin{bmatrix}
    1&0&0\\
    \frac{1}{2}&1&0\\
    1&1&1\\
\end{bmatrix}\begin{bmatrix}
    2&2&4\\
    0&-1&1\\
    0&0&-3\\
\end{bmatrix}
$$

```{julia}
#| label: lu-decomp
# Define matrix.
A = [[2,1,2] [2,0,1] [4,3,2]]
println("A = $A")
# Perform LU decomposition.
A_LU_all = LinearAlgebra.lu(A)
L = A_LU_all.L
U = A_LU_all.U
println("L = $L")
println("U = $U")
```
## Row swapping with Permutation matrices
- Some matrices are hard to transform into upper-triangular form.
- We can swap rows to help put it in echelon form and then perform row reduction from there. This is done with a permutation matrix.
- Numerical example:
    - Original matrix
    $$
    \begin{bmatrix}
        3&2&1\\
        0&5&5\\
        0&7&2\\
    \end{bmatrix}
    $$
    - Row swapping with the permutation matrix, $P$:
    $$
    \begin{bmatrix}
        1&0&0\\
        0&1&1\\
        0&1&0\\
    \end{bmatrix}\begin{bmatrix}
        3&2&1\\
        0&5&5\\
        0&7&2\\
    \end{bmatrix} = \begin{bmatrix}
        3&2&1\\
        0&7&2\\
        0&0&5\\
    \end{bmatrix}
    $$
- Often this is required with LU decomposition. So technically, LU decomposition is denoted as:
$$
PA = LU\\
A = P^TLU
$$
- Permutation matrices are orthogonal. Which means $P^{-1} = P^T$ and $P^TP = I$.
