name = "linear_algebra"
uuid = "9841dd11-8ffd-44fc-8c43-eaf31a7d027e"
authors = ["DamonCharlesRoberts <damon.charles.roberts@gmail.com>"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
